apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "skool-mvp-web.fullname" . }}
  {{- if .Values.namespace }}
  namespace: {{ .Values.namespace | quote }}
  {{- end }}
  labels:
    {{- include "skool-mvp-web.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "skool-mvp-web.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "skool-mvp-web.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: skool-mvp-web
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
          env:
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
